#+title: org-percentile: Live percentile feedback from Org clocks
#+author: Pablo Stafforini
#+language: en
#+options: ':t toc:nil author:t email:t
#+startup: content

This manual describes the Emacs package =org-percentile=.

** Overview
:PROPERTIES:
:CUSTOM_ID: h:a09b70a2-ae0b-4855-ac14-1dddfc8e3241
:ID:       86021BE2-A5C7-42E3-89BF-AFD80E92A7AF
:END:

=org-percentile= implements Seth Roberts’ “percentile feedback”
productivity metric. It provides a live indicator in your mode-line
that shows your current productivity percentile relative to your past
performance.

The package is tightly integrated with Org mode's clocking functionality.
It automatically logs your work periods when you use =org-clock-in= and
=org-clock-out=.

The core idea is to give you a continuous, real-time measure of how
your current day's productivity compares to previous days at the same
time. This can help you stay motivated and adjust your effort as needed.

** Installation
:PROPERTIES:
:ID:       A157F078-925A-4232-A982-59D3358167FB
:END:

*** Manual
:PROPERTIES:
:ID:       EB432794-7213-4027-949A-313218C7566B
:END:

Clone this repository to your Emacs load path and add this to your =init.el= file:

#+begin_src emacs-lisp
(require 'org-percentile)
#+end_src

*** With =use-pacakge=
:PROPERTIES:
:ID:       8BA1C103-6B36-4D66-A0F1-9E1297788196
:END:
If you use =use-package=, add this your =init.el= file:

#+begin_src emacs-lisp
;; with vc
(use-package org-percentile
  :vc (:url "https://github.com/benthamite/org-percentile"))

;; with elpaca
(use-package org-percentile
  :ensure (:host github :repo "benthamite/org-percentile"))

;; with straight
(use-package org-percentile
  :straight (:host github :repo "benthamite/org-percentile"))

;; with quelpa
(use-package org-percentile
  :quelpa (org-percentile :fetcher github :repo "benthamite/org-percentile"))
        #+end_src

** Sample configuration
:PROPERTIES:
:CUSTOM_ID: h:5d16932d-4f7b-493d-8e6a-e5c396b15fd6
:ID:       AC9FDD00-8F52-48C6-AD16-BA754EBED8BF
:END:

A minimal setup to get started:

#+begin_src emacs-lisp
(require 'org-percentile)

;; Enable the mode to start tracking and see the mode-line indicator.
(org-percentile-mode 1)

;; Optionally, specify Org files to import historical clock data from.
(setq org-percentile-org-files '("~/org/work.org" "~/org/personal.org"))

;; Import the data.
(org-percentile-import-org-files)
#+end_src

** How it works
:PROPERTIES:
:CUSTOM_ID: h:17896c8c-d97a-4faa-abf6-31df99746ca6
:ID:       E3E49E55-A1B8-4D2D-889D-7EAE6E94513C
:END:

=org-percentile= works by hooking into Org mode's clocking commands.

- When you clock in with =org-clock-in=, the mode-line indicator is updated.
- When you clock out with =org-clock-out=, the completed work period is
  logged to the data file specified by =org-percentile-data-file=. The
  mode-line is updated, and a message shows your new percentile.

The percentile is calculated by comparing your total clocked time for
the current day (up to the current time) with the total clocked time
from all previous days (up to the same time of day).

For example, if it's 2 PM and you've worked 4 hours today, =org-percentile=
will check what percentage of past days you had worked 4 hours or less by 2 PM.
If on 80% of the days you had worked 4 hours or less, your current
percentile is 80%.

** Commands
:PROPERTIES:
:CUSTOM_ID: h:6a92a8b5-d766-42cc-8e5b-8dc255466a23
:ID:       E4D5F444-C2CC-4800-A0DD-2CB7EE7FBEBB
:END:

*** =org-percentile-mode=
:PROPERTIES:
:ID:       C6BD047A-1486-45AA-862A-ECE62C32E83C
:END:
A global minor mode that activates and deactivates the percentile
feedback functionality. When enabled, it adds hooks to =org-clock= and
displays the percentile in the mode-line.

*** =org-percentile-import-org-files=
:PROPERTIES:
:ID:       C9283E78-EAE8-4445-8FDA-E9D4C60CE688
:END:
This command parses all =CLOCK= entries from the files listed in
=org-percentile-org-files= and adds them to the history data. This is
useful for bootstrapping the system with your existing Org clock data.

** Customization
:PROPERTIES:
:CUSTOM_ID: h:f9204f1f-fcee-49b1-8081-16a08a338099
:ID:       17615C1C-4D0C-4A8B-99D0-DCDDD0CE9015
:END:

*** =org-percentile-data-file=
:PROPERTIES:
:ID:       DF960394-02AE-4EFF-9270-39892A65FA18
:END:
The file where percentile feedback history is stored. Defaults to
=~/.emacs.d/org-percentile-data.el=.

*** =org-percentile-org-files=
:PROPERTIES:
:ID:       8307CD55-65A9-4C0A-86F6-3EA87ED41D79
:END:
An optional list of Org files whose =CLOCK= entries can be imported
using =org-percentile-import-org-files=.

*** =org-percentile-midnight-shift=
:PROPERTIES:
:ID:       A051E1E9-15FF-4350-80BA-B8028643F450
:END:
This variable determines what time is considered "midnight" for the
purpose of calculating daily work periods. It defaults to the value of
=org-extend-today-until=. For example, a value of 21600 means your
"day" starts at 6 AM.

** Contributing
:PROPERTIES:
:CUSTOM_ID: h:1ebe4865-c001-4747-a6f2-0fe45aad71cd
:ID:       8181416C-4A32-4F68-8206-531D84A2ABE8
:END:

Contributions are welcome. Please open an issue or pull request on the
project's repository.

** License
:PROPERTIES:
:CUSTOM_ID: h:40b18bb2-4dc1-4202-bd0b-6fab535b2a0f
:ID:       E60A8D6C-56F0-477B-8802-7F14B01C6C36
:END:

This package is distributed under the MIT License.
